---
title: "About"
title-block-banner: telescope.jpeg
title-block-banner-color: white
---
Hi! Thanks for visiting my site. I've tried to compile some resources for students interested in pursuing economics as a predoc in my resources page. Here, I'll talk a little bit about myself. 

I'm a PhD student at Stanford. When I'm not working, I bird- mushroom- plant- etc.- watch and appreciate the [biodiversity of California](https://www.cepf.net/our-work/biodiversity-hotspots/california-floristic-province)!
 
I also donate blood with the [Stanford Blood Center](https://sbcdonor.org/donor/schedules/zip) as often as I am eligible and would encourage anyone who is eligible to consider doing so as well. 
Being a consistent donor can be especially helpful for patients who receive frequent blood transfusions and need a good match on antibodies outside of (A, B, O, Rh +/-). 

I attended Wellesley College, a historically women's college, where I majored in economics and math.
Before I became an economist, I interned at NASA for two summers and got to see a lot of cool things, like the [James Webb Space Telescope](https://www.jwst.nasa.gov/) before it went into space.
I also got to work with [Wellesley's 171-year-old telescope](https://www.wellesley.edu/astronomy/whitin/fitzclark), and hope I can find time to pick up recreational astronomy again in the future.
Many government agencies have internship programs for high school and college students (that aren't publicized that well), so if you're interested in working in the public sector, I'd encourage you to check them out, like NASA's program [here](https://www.nasa.gov/learning-resources/internship-programs/).